# Matrix-Multiplication 


## 2D/3D matrix-multiplication using `python3`

##### In linear algebra and machine learning, matrix multiplication is a fundamental concept. 
##### There is many ways to add and multiply matrices mathematically and programmatically. 
##### Here are some implemenations purely using python.

In [1]:
!pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/9b/5a/f265a1ba3641d16b5480a217a6aed08cceef09cd173b568cd5351053472a/numpy-1.26.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.5/58.5 kB 822.7 kB/s eta 0:00:001m448.3 kB/s eta 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.2/18.2 MB 28.7 MB/s eta 0:00:00m eta 0:00:010:01:01


In [8]:
!pip install torch

  Using cached torch-2.0.1-cp310-cp310-manylinux1_x86_64.whl (619.9 MB)
  Obtaining dependency information for filelock from https://files.pythonhosted.org/packages/5e/5d/97afbafd9d584ff1b45fcb354a479a3609bd97f912f8f1f6c563cb1fae21/filelock-3.12.4-py3-none-any.whl.metadata
  Using cached sympy-1.12-py3-none-any.whl (5.7 MB)
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
  Using cached nvidia_cuda_nvrtc_cu11-11.7.99-2-py3-none-manylinux1_x86_64.whl (21.0 MB)
  Using cached nvidia_cuda_runtime_cu11-11.7.99-py3-none-manylinux1_x86_64.whl (849 kB)
  Using cached nvidia_cuda_cupti_cu11-11.7.101-py3-none-manylinux1_x86_64.whl (11.8 MB)
  Using cached nvidia_cudnn_cu11-8.5.0.96-2-py3-none-manylinux1_x86_64.whl (557.1 MB)
  Using cached nvidia_cublas_cu11-11.10.3.66-py3-none-manylinux1_x86_64.whl (317.1 MB)
  Using cached nvidia_cufft_cu11-10.9.0.58-py3-none-manylinux1_x86_64.whl (168.4 MB)
  Using cached nvidia_curand_cu11-10.2.10.91-py3-none-manylinux1_x86_64.whl (54.6 MB)
  Using cac

##### Import the **`numpy`** library. This is necessary for advanced computations and comprehensive mathematical functions.

In [2]:
import numpy as np

##### Import the **`PyTorch`** library. This is necessary because we will be using `torch` tensors to represent our matrices.

In [9]:
import torch

In [5]:
# Create matrices using np.arange and np.reshape which are two 3x3 matrices
matrix_1 = np.arange(1,10).reshape(3,3)

matrix_2 = np.arange(0,9).reshape(3,3)

# Calculate the dot product of matrix_1 and matrix_2 using NumPy's dot function
res = np.dot(matrix_1,matrix_2)

# Print resulting matrix
print(res)

[[ 24  30  36]
 [ 51  66  81]
 [ 78 102 126]]


##### You saw the first method which utilizes `numpy`, this next method involves using nested for loops. Use nested for loops to iterate through rows and columns of the matrices. The code uses three nested for loops to iterate through the rows and columns of `matrix_1` and `matrix_2`. For each row `i` in `matrix_1` and each column `j` in `matrix_2`, the code calculates the element at row `i` and column `j` of the result matrix `res`.

In [7]:
# Input two matrices and label them

matrix_1 = [[1,2,3],
            [4,5,6],
            [7,8,9]]
matrix_2 = [[0,1,2],
            [3,4,5],
            [6,7,8]]

# Create an empty result matrix to store the multiplication result
res = [[0 for x in range (3)] for y in range(3)]

# Use nested for loops to iterate through rows and columns of the matrices
for i in range(len(matrix_1)):
    for j in range(len(matrix_2[0])):
        for k in range(len(matrix_2)):

            # Calculate the element at row 'i' and column 'j' of the result matrix
            res[i][j] += matrix_1[i][k] * matrix_2[k][j]

# Print the resulting matrix
print(res)

[[24, 30, 36], [51, 66, 81], [78, 102, 126]]


##### The last method involves using **`pytorch`**. Tensors in `torch` can be scalars, vectors, and matrices.

In [10]:
# Define two matrices as PyTorch tensors

matrix_1 = torch.tensor([[1,2,3],
                        [4,5,6],
                        [7,8,9]])

matrix_2 = torch.tensor([[0,1,2],
                        [3,4,5],
                        [6,7,8]])

# Calculate the dot product of matrix_1 and matrix_2 using .matmul()
product = torch.matmul(matrix_1, matrix_2)

# Print resulting matrix
print(product)

tensor([[ 24,  30,  36],
        [ 51,  66,  81],
        [ 78, 102, 126]])
